graph TD
    A[Início]
    A --> B[Planejamento e Análise de Requisitos]
    B --> C[Design e Modelagem]
    C --> |Modelagem de Ameaças| D[Desenvolvimento e Codificação]
    C --> |Design de Arquitetura| D
    C --> |Design de UI/UX| D
    D --> E[Testes]
    E --> F[DevSecOps e Segurança]
    F --> G[CI/CD]
    G --> H[Deploy e Entrega Contínua]
    H --> I[Monitoramento e Manutenção]
    I --> J[Feedback e Iteração]
    J --> K[Documentação e Conhecimento]
    K --> L[Gestão de Projeto]
    L --> M[Feedback e Avaliação]
    M --> N[Próximo Ciclo]
