graph TD
    A[Início]
    A --> B[Ideação e Conceituação]
    B --> C[Planejamento e Análise de Requisitos Detalhada]
    C --> D[Avaliação de Riscos e Conformidade]
    D --> E[Design e Modelagem]
    E --> |Modelagem de Ameaças| F[Prototipagem e Design Iterativo]
    E --> |Design de Arquitetura| F
    E --> |Design de UI/UX| F
    F --> G[Desenvolvimento e Codificação]
    G --> H[TDD: Desenvolvimento Orientado a Testes]
    H --> I[Testes Unitários e de Integração]
    I --> J[Revisão de Código e QA]
    J --> K[Testes de Sistema]
    K --> |Testes de Sistema| L[DevSecOps e Segurança]
    K --> |Testes de Aceitação do Usuário| L
    L --> M[Implementação de CI/CD]
    M --> N[Deploy e Entrega Contínua]
    N --> O[Monitoramento e Manutenção]
    O --> P[Feedback e Iteração Pós-Lançamento]
    P --> Q[Documentação e Conhecimento]
    Q --> R[Gestão de Projeto]
    R --> S[Feedback e Avaliação]
    S --> T[Planejamento de Descontinuação]
    T --> U[Próximo Ciclo]