graph TD
    A[Defição do Objetivo do Software] --> B[Identificação dos Stakeholders]
    B --> C[Entrevistas e Reuniões]
    C --> D[Analise dos dados obtidos e documentos]
    D --> E[Documentação dos Requisitos]
    E --> F[Priorização dos Requisitos]
    F --> G[Criação de Personas para testes]
    G --> H[Validação dos Requisitos]
    H --> I[Revisões dos Requisitos e continuidade]
    I --> J[Definição das Ferramentas]
    J --> K[Definição da Comunicação]
    K --> L[Planejamento de Manutenção e Ajustes]
